import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRolesAndPermissions1771172953629 implements MigrationInterface {
    name = 'AddRolesAndPermissions1771172953629'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "resource" character varying(50) NOT NULL, "permission" character varying(20) NOT NULL, CONSTRAINT "UQ_dad78e0a596f4610d567640beb8" UNIQUE ("role_id", "resource", "permission"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(500), "is_system" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "UQ_23ed6f04fe43066df08379fd034" UNIQUE ("user_id", "role_id"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contact_person" character varying, "email" character varying, "phone" character varying, "address" text, "website" character varying, "notes" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "product_id" uuid NOT NULL, "supplier_sku" character varying, "cost_per_unit" numeric(12,2), "lead_time_days" integer, "minimum_order_quantity" integer, "is_preferred" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_651e91706e362ef7393457c347e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "parent_id" uuid, "description" character varying(500), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character varying(255), "updated_by" character varying(255), "deleted_by" character varying(255), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sku" character varying(50) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "category_id" uuid NOT NULL, "brand_id" uuid, "volume_ml" integer, "weight_kg" numeric(10,3), "dimensions_cm" character varying(50), "standard_cost" numeric(12,2), "standard_price" numeric(12,2), "markup_percentage" numeric(6,2), "reorder_point" integer NOT NULL DEFAULT '0', "primary_supplier_id" uuid, "supplier_sku" character varying(50), "barcode" character varying(100), "unit" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "is_perishable" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d83923034b9d107f2cdf1508f0" ON "products" ("category_id", "deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f1ee13b28429d25edab91fc61" ON "products" ("is_active", "deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_718dfbc007ec098cfa28295ca7" ON "products" ("deleted_at") `);
        await queryRunner.query(`CREATE TYPE "public"."locations_type_enum" AS ENUM('WAREHOUSE', 'SUPPLIER', 'IN_TRANSIT', 'CLIENT')`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."locations_type_enum" NOT NULL, "address" text NOT NULL DEFAULT '', "contact_person" character varying NOT NULL DEFAULT '', "phone" character varying NOT NULL DEFAULT '', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clients_account_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "clients" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_name" character varying NOT NULL, "yacht_name" character varying, "contact_person" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "billing_address" text, "default_delivery_address" text, "account_status" "public"."clients_account_status_enum" NOT NULL DEFAULT 'ACTIVE', "payment_terms" character varying, "credit_limit" numeric(12,2), "notes" text, CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1615829831511a85c595a89bbe" ON "clients" ("account_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48860677afe62cd96e1265948" ON "clients" ("email") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(12,2) NOT NULL, "subtotal" numeric(12,2) NOT NULL, "notes" text, "quantity_picked" integer NOT NULL DEFAULT '0', "quantity_packed" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9263386c35b6b242540f9493b0" ON "order_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_145532db85752b29c57d2b7b1f" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('DRAFT', 'CONFIRMED', 'SOURCING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'ON_HOLD')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying NOT NULL, "client_id" uuid NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'DRAFT', "delivery_deadline" TIMESTAMP WITH TIME ZONE, "delivery_address" text NOT NULL, "yacht_name" character varying, "special_instructions" text, "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "assigned_to" uuid, "created_by" uuid NOT NULL, "confirmed_at" TIMESTAMP WITH TIME ZONE, "shipped_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "kanban_task_id" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_505ba3689ef2763acd6c4fc93a" ON "orders" ("client_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_75eba1c6b1a66b09f2a97e6927" ON "orders" ("order_number") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_reason_enum" AS ENUM('PURCHASE_RECEIVE', 'SALE', 'WASTE', 'DAMAGED', 'EXPIRED', 'COUNT_CORRECTION', 'RETURN_FROM_CLIENT', 'RETURN_TO_SUPPLIER', 'INTERNAL_TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "from_location_id" uuid, "to_location_id" uuid, "quantity" integer NOT NULL, "reason" "public"."stock_movements_reason_enum" NOT NULL, "order_id" uuid, "reference_number" character varying, "cost_per_unit" numeric(12,2), "kanban_task_id" character varying, "user_id" uuid NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2da8647ef82e50376cfc1ae7f" ON "stock_movements" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_058f5f7410f62bbec24316f447" ON "stock_movements" ("reason") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d6a3879be507d2a0a56b7ed27" ON "stock_movements" ("to_location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_be050cac39912970f8a02fa3d9" ON "stock_movements" ("from_location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c1bb05b80ddcc562cd28d826c" ON "stock_movements" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "url" text NOT NULL, "caption" text, "display_order" integer NOT NULL DEFAULT '0', "uploaded_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location_id" uuid NOT NULL, "parent_id" uuid, "name" character varying(100) NOT NULL, "code" character varying(50) NOT NULL DEFAULT '', "description" text NOT NULL DEFAULT '', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5110493f6342f34c978c084d0d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_763f110709cdcd193a5e43d7b6" ON "areas" ("location_id", "parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_86373c0dc23df246c2b6ac977c" ON "areas" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f2e4e10bf85d7a06ffb7c02b9" ON "areas" ("location_id") `);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "location_id" uuid NOT NULL, "area_id" uuid, "quantity" integer NOT NULL DEFAULT '0', "batch_number" character varying NOT NULL DEFAULT '', "expiry_date" TIMESTAMP WITH TIME ZONE, "cost_per_unit" numeric(12,2), "received_date" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_803183847ddb35e24b2544976e" ON "inventory" ("product_id", "location_id", "area_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a51c510e8ff4ee67d9376d8851" ON "inventory" ("product_id", "location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e567ec7296efc2d20f3d58f70a" ON "inventory" ("area_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1eea99c8c645d7541002473a01" ON "inventory" ("location_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_732fdb1f76432d65d2c136340d" ON "inventory" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "branding_settings" ("id" integer NOT NULL DEFAULT '1', "app_name" character varying(100) NOT NULL DEFAULT 'LibreStock', "tagline" character varying(255) NOT NULL DEFAULT 'Inventory management system', "logo_url" character varying(500), "favicon_url" character varying(500), "primary_color" character varying(7) NOT NULL DEFAULT '#3b82f6', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" character varying, CONSTRAINT "PK_ec51d33cc5ec38420355309bfab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'ADJUST_QUANTITY', 'ADD_PHOTO', 'STATUS_CHANGE')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entity_type_enum" AS ENUM('PRODUCT', 'CATEGORY', 'SUPPLIER', 'ORDER', 'ORDER_ITEM', 'INVENTORY', 'LOCATION', 'STOCK_MOVEMENT', 'PHOTO', 'AREA', 'CLIENT', 'ROLE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" "public"."audit_logs_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "changes" jsonb, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_products" ADD CONSTRAINT "FK_4286173e1486a5c528f89dc798c" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9b6ec6b7a2e6772110b28f89bf1" FOREIGN KEY ("primary_supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_505ba3689ef2763acd6c4fc93a4" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_2c1bb05b80ddcc562cd28d826c6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_be050cac39912970f8a02fa3d92" FOREIGN KEY ("from_location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_4d6a3879be507d2a0a56b7ed276" FOREIGN KEY ("to_location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_8311bb94d8e30b9995383801e3d" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "areas" ADD CONSTRAINT "FK_8f2e4e10bf85d7a06ffb7c02b94" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "areas" ADD CONSTRAINT "FK_86373c0dc23df246c2b6ac977c3" FOREIGN KEY ("parent_id") REFERENCES "areas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_732fdb1f76432d65d2c136340dc" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_1eea99c8c645d7541002473a015" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_e567ec7296efc2d20f3d58f70a7" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_e567ec7296efc2d20f3d58f70a7"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_1eea99c8c645d7541002473a015"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_732fdb1f76432d65d2c136340dc"`);
        await queryRunner.query(`ALTER TABLE "areas" DROP CONSTRAINT "FK_86373c0dc23df246c2b6ac977c3"`);
        await queryRunner.query(`ALTER TABLE "areas" DROP CONSTRAINT "FK_8f2e4e10bf85d7a06ffb7c02b94"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_8311bb94d8e30b9995383801e3d"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_4d6a3879be507d2a0a56b7ed276"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_be050cac39912970f8a02fa3d92"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_2c1bb05b80ddcc562cd28d826c6"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_505ba3689ef2763acd6c4fc93a4"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9b6ec6b7a2e6772110b28f89bf1"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "supplier_products" DROP CONSTRAINT "FK_4286173e1486a5c528f89dc798c"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "branding_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_732fdb1f76432d65d2c136340d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1eea99c8c645d7541002473a01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e567ec7296efc2d20f3d58f70a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a51c510e8ff4ee67d9376d8851"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_803183847ddb35e24b2544976e"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f2e4e10bf85d7a06ffb7c02b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86373c0dc23df246c2b6ac977c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_763f110709cdcd193a5e43d7b6"`);
        await queryRunner.query(`DROP TABLE "areas"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c1bb05b80ddcc562cd28d826c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be050cac39912970f8a02fa3d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d6a3879be507d2a0a56b7ed27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_058f5f7410f62bbec24316f447"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2da8647ef82e50376cfc1ae7f"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75eba1c6b1a66b09f2a97e6927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_505ba3689ef2763acd6c4fc93a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9263386c35b6b242540f9493b0"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b48860677afe62cd96e1265948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1615829831511a85c595a89bbe"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TYPE "public"."clients_account_status_enum"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TYPE "public"."locations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_718dfbc007ec098cfa28295ca7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f1ee13b28429d25edab91fc61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d83923034b9d107f2cdf1508f0"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "supplier_products"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
    }

}
